# Generated by Django 4.2.4 on 2023-08-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valence', models.IntegerField(default=0)),
                ('arousal', models.IntegerField(default=0)),
                ('complexity', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Hip-Hop', 'Hip-Hop')], default='Rock', max_length=50)),
                ('is_playing', models.BooleanField(default=False)),
            ],
        ),
    ]
